############################################################
#
# web访问端口号  约定：8088
#
############################################################
server:
  port: 8088

############################################################
#
# 配置数据源信息
#
############################################################
spring:
  datasource:                                           # 数据源的相关配置
    url: jdbc:mysql://localhost:3306/foodie?useUnicode=true&characterEncoding=UTF-8&autoReconnect=true&serverTimezone=UTC
    password: root
  redis:                          # redis集群配置
    password: 123456
    cluster:
      nodes: 172.16.57.140:6379,172.16.57.141:6379,172.16.57.142:6379,172.16.57.143:6379,172.16.57.144:6379,172.16.57.145:6379

  # redis 单机单实力
    # database: 1
    # host: 172.16.57.137
    # port: 6379
    # password: 123456
    # redis 哨兵模式
    # database: 1
    # password: 123456
    # sentinel:
    #   master: mymaster
    #   nodes: 172.16.57.137:26379,172.16.57.138:26379,172.16.57.139:26379

############################################################
#
# mybatis 配置
#
############################################################
mybatis:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl