server:
  port: 8099

spring:
  datasource: # 数据源的相关配置
    type: com.zaxxer.hikari.HikariDataSource            # 数据源类型：HikariCP
    driver-class-name: com.mysql.cj.jdbc.Driver         # mysql驱动
    url: jdbc:mysql://localhost:3306/foodie?useUnicode=true&characterEncoding=UTF-8&autoReconnect=true&serverTimezone=UTC
    username: root
    password: root
    hikari:
      connection-timeout: 30000       # 等待连接池分配连接的最大时长（毫秒），超过这个时长还没可用的连接则发生SQLException， 默认:30秒
      minimum-idle: 5                 # 最小连接数 上线修改为10
      maximum-pool-size: 20           # 最大连接数
      auto-commit: true               # 自动提交
      idle-timeout: 600000            # 连接超时的最大时长（毫秒），超时则被释放（retired），默认:10分钟
      pool-name: DateSourceHikariCP   # 连接池名字
      max-lifetime: 1800000           # 连接的生命时长（毫秒），超时而且没被使用则被释放（retired），默认:30分钟 1800000ms
      connection-test-query: SELECT 1
  rabbitmq:
    addresses: 172.16.57.153:5672,172.16.57.154:5672,172.16.57.155:5672
    username: admin
    password: admin
    virtual-host: /
    connection-timeout: 15000
    listener:
      simple:
        acknowledge-mode: manual          # 表示消费者消费成功消息以后需要手工的进行签收(ack)，默认auto
        concurrency: 5
        max-concurrency: 10
        prefetch: 1

logging:
  config: classpath:logback-springdev.xml
