############################################################
#
# web访问端口号  约定：8090
#
############################################################
server:
  tomcat:
    uri-encoding: UTF-8
  max-http-header-size: 80KB

############################################################
#
# 配置数据源信息
#
############################################################
spring:
  profiles:
    active: dev
    include: devfile
  servlet:
    multipart:
      max-file-size: 51200                             # 文件上传大小限制500kb
      max-request-size: 51200                           # 请求大小限制为500kb
  datasource:                                           # 数据源的相关配置
    type: com.zaxxer.hikari.HikariDataSource            # 数据源类型：HikariCP
    driver-class-name: com.mysql.cj.jdbc.Driver         # mysql驱动
    username: root
    hikari:
      connection-timeout: 30000       # 等待连接池分配连接的最大时长（毫秒），超过这个时长还没可用的连接则发生SQLException， 默认:30秒
      minimum-idle: 5                 # 最小连接数 上线修改为10
      maximum-pool-size: 20           # 最大连接数
      auto-commit: true               # 自动提交
      idle-timeout: 600000            # 连接超时的最大时长（毫秒），超时则被释放（retired），默认:10分钟
      pool-name: DateSourceHikariCP   # 连接池名字
      max-lifetime: 1800000           # 连接的生命时长（毫秒），超时而且没被使用则被释放（retired），默认:30分钟 1800000ms
      connection-test-query: SELECT 1
  thymeleaf:
    mode: HTML
    encoding: UTF-8
    prefix: classpath:/templates/
    suffix: .html

logging:
  config: classpath:logback-springdev.xml