server:
  port: 8066

spring:
  profiles:
    include: devfile
  datasource:                                           # 数据源的相关配置
    type: com.zaxxer.hikari.HikariDataSource            # 数据源类型：HikariCP
    driver-class-name: com.mysql.cj.jdbc.Driver         # mysql驱动
    url: jdbc:mysql://localhost:3306/foodie?useUnicode=true&characterEncoding=UTF-8&autoReconnect=true&serverTimezone=UTC
    username: root
    password: root
    hikari:
      connection-timeout: 30000       # 等待连接池分配连接的最大时长（毫秒），超过这个时长还没可用的连接则发生SQLException， 默认:30秒
      minimum-idle: 5                 # 最小连接数 上线修改为10
      maximum-pool-size: 20           # 最大连接数
      auto-commit: true               # 自动提交
      idle-timeout: 600000            # 连接超时的最大时长（毫秒），超时则被释放（retired），默认:10分钟
      pool-name: DateSourceHikariCP   # 连接池名字
      max-lifetime: 1800000           # 连接的生命时长（毫秒），超时而且没被使用则被释放（retired），默认:30分钟 1800000ms
      connection-test-query: SELECT 1
  redis:                              # redis集群配置
    password: 123456
    cluster:
      nodes: 172.16.57.140:6379,172.16.57.141:6379,172.16.57.142:6379,172.16.57.143:6379,172.16.57.144:6379,172.16.57.145:6379

############################################################
#
# mybatis 配置
#
############################################################
mybatis:
  type-aliases-package: com.sr.pojo          # 所有POJO类所在包路径
  mapper-locations: classpath:mapper/*.xml   # mapper映射文件

############################################################
#
# mybatis mapper 配置
#
############################################################
# 通用 Mapper 配置
mapper:
  mappers: com.sr.my.mapper.MyMapper
  not-empty: false  # 在进行数据库操作的的时候，判断表达式 username != null, 是否追加 username != ''
  identity: MYSQL
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

# 分页插件配置
pagehelper:
  support-methods-arguments: true

logging:
  config: classpath:logback-springdev.xml

fdfs:
  connect-timeout: 30               # 连接的超时时间
  so-timeout: 30                    # 读取的超时时间
  tracker-list: 172.16.57.151:22122 # tracker服务器地址